version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.1.1
    restart: always
    ports:
      - 9200:9200
    volumes:
      - ${ELASTICSEARCH_PATH_DATA}:/usr/share/elasticsearch/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  kibana:
    image: kibana:5.1.1
    restart: always
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  logstash:
    image: logstash:5.1.1
    restart: always
    command: logstash -f /config-dir/logstash.conf
    ports:
      - 5000:5000
    links:
      - elasticsearch
    volumes:
      - ${LOGSTASH_PATH_CONFIG}:/config-dir
    logging:
      options:
        max-size: "10m"
        max-file: "10"